package jsonvalues.spec;

public enum ERROR_CODE {
    STRING_EXPECTED,
    STRING_CONDITION,
    INT_EXPECTED,
    BINARY_EXPECTED,
    INSTANT_EXPECTED,
    INT_CONDITION,
    LONG_EXPECTED,
    LONG_CONDITION,
    BOOLEAN_EXPECTED,
    BOOLEAN_CONDITION,
    INTEGRAL_EXPECTED,
    INTEGRAL_CONDITION,
    DECIMAL_EXPECTED,
    DECIMAL_CONDITION,
    TRUE_EXPECTED,
    FALSE_EXPECTED,
    OBJ_EXPECTED,
    OBJ_CONDITION,
    BINARY_CONDITION,
    ARRAY_EXPECTED,
    ARRAY_CONDITION,
    NUMBER_EXPECTED,
    NUMBER_CONDITION,
    INSTANT_CONDITION,
    NULL,
    NULL_EXPECTED,
    REQUIRED,
    VALUE_CONDITION,
    SPEC_MISSING,
    CONSTANT_CONDITION,

    ARR_SIZE_LOWER_THAN_MIN,

    ARR_SIZE_GREATER_THAN_MAX
}
